version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=dev_key_for_development
      - MAIL_SERVER=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USERNAME=your_email@example.com
      - MAIL_PASSWORD=your_password
      - MAIL_DEFAULT_SENDER=noreply@example.com
      - ADMIN_EMAIL=admin@example.com
      - APP_URL=http://localhost:5001
    volumes:
      - .:/app
    restart: always 